### ISSUE TITLE
Move `jupyterlab-lsp` server extension into `jupyter-server` organization

### ISSUE THREAD

**Issue by trungleduc** [jupyter-server/team-compass#30]
There is an ongoing effort to add the support of the Language Server Protocol into core JupyterLab.

1. Michał Krassowski opened a JEP ([#72](https://github.com/jupyter/enhancement-proposals/pull/72)) proposing the adoption of LSP as part of Jupyter for notebooks. This was approved and merged in September 2021.

2. Most of the work on LSP in Jupyter lives in the jupyterlab-lsp project, mostly maintained by Michał Krassowski (@krassowski) and Nick Bollweg (@bollwyvl ).

4. I have been working on integrating some foundational parts of the logic of `jupyterlab-lsp` in core JupyterLab. In PR https://github.com/jupyterlab/jupyterlab/pull/12534, core components of the `jupyterlab-lsp` frontend extension handling the language server initialization and communication are moved into a new "lsp" package of JupyterLab.
This work has already been extensively discussed in dedicated meetings with the developers of `jupyterlab-lsp`

5. A natural next step would be to create a new repository in jupyter-server incorporating the pure server-side parts of `jupyterlab-lsp`([jupyter-lsp](https://github.com/jupyter-lsp/jupyterlab-lsp/tree/master/python_packages/jupyter_lsp)), and make it a dependency of `jupyterlab-server` (https://github.com/jupyterlab/jupyterlab_server/pull/282).

For reference, a JupyterLab team compass issue is opened here on the same subject: https://github.com/jupyterlab/team-compass/issues/148.
Ping @bollwyvl and @krassowski, please feel free to comment or correct me if I misrepresented anything.

Votes

- @damianavila 
  - [ ] yes
  - [ ] no 
- @kevin-bates 
  - [x] yes
  - [ ] no 
- @echarles 
  - [ ] yes
  - [ ] no 
- @SylvainCorlay 
  - [ ] yes
  - [ ] no 
- @afshin 
  - [ ] yes
  - [ ] no 
- @vidartf  
  - [ ] yes
  - [ ] no 
- @rahul26goyal  
  - [ ] yes
  - [ ] no 
- @ellisonbg 
  - [x] yes
  - [ ] no 
- @ivanov  
  - [ ] yes
  - [ ] no 
- @lresende  
  - [ ] yes
  - [ ] no 
- @Zsailer  
  - [x] yes
  - [ ] no 
- @blink1073  
  - [x] yes
  - [ ] no 
- @willingc  
  - [x] yes
  - [ ] no 
- @jess-x  
  - [ ] yes
  - [ ] no

**Comment by Zsailer** [comment]
Sorry there hasn't been any movement on this. Let's discuss this again at our next meeting. 

Pinging the @jupyter-server/jupyter-server-council to review this proposal and respond.

**Comment by ellisonbg** [comment]
Can someone give me permissions to this repo so I can vote...

**Comment by Zsailer** [comment]
:+1:  @ellisonbg, just sent you an invitation to join the Jupyter Server org.

**Comment by krassowski** [comment]
A potential downside of this proposal is that moving issues between organizations is annoying. We often bump into this for notebook/lab/server during Thursday triage meetings (and often no one has sufficient permissions to ask our friend meseeksdev to move issues), and I suspect it might be an issue with LSP which under this proposal will live in 3 organizations for some time: JupyterLab (core), jupyter-lsp (extra features), jupyter-server and users will have no clue where to report.

**Comment by krassowski** [comment]
A potential downside of this proposal is that moving issues between organizations is annoying. We often bump into this for notebook/lab/server during Thursday triage meetings (and often no one has sufficient permissions to ask our friend meseeksdev to move issues), and I suspect it might be an issue with LSP which under this proposal will live in 3 organizations for some time: JupyterLab (core), jupyter-lsp (extra features), jupyter-server and users will have no clue where to report.

**Comment by Zsailer** [comment]
@krassowski yes, this is a great point. 

This issue was mentioned during the Jupyter Server team meeting where this org transfer was first proposed. I think you and the rest of the LSP maintainers should definitely take some time to consider if this is the best move forward for the project. 

In the meantime, we can continue the vote here. That way, we will know if the server team is willing to receive the (server-side) project as something they will shepherd.

If it's accepted, the LSP maintainers can still decide they don't want to do the transfer after all.

**Comment by krassowski** [comment]
Just to clarify, I was not saying that I oppose the move, but that it might make our lives easier if we have a repo in `jupyter-lsp` organisation.

Some other points:
- If I were a new contributor I would expect to find `jupyter-lsp` server extension in `jupyter-lsp` organization
- on the point about issues: how frequently do we expect to move issues between `jupyterlab-lsp` and `jupyter-lsp` and how frequently between `jupyter-lsp` and `jupyter-server` (or other repos in this org)?
- maybe we should rename `jupyter-lsp` repo to `jupyter-lsp-server`?
- we can add designated members (or everyone) from jupyter-server team who would need access to the `jupyter-lsp` organization and create a GitHub team with privileges to that repo so that everyone can triage/release as appropriate

I am _really_ looking forward to moving the server extension out of the current monorepo at https://github.com/jupyter-lsp/jupyterlab-lsp - it would simplify moving to jupyter-releaser, dealing with changelogs and also make first contributions easier.

I think I prefer if that would be under `https://github.com/jupyter-lsp` organization, but I don't feel strongly about it. @trungleduc what do you think? If you are available, let's get this done by the end of next week.

**Comment by trungleduc** [comment]
Hi @krassowski, thanks for your clarification. I have no objection to keeping the `jupyter-lsp` server extension in the `jupyter-lsp` organization. 
Since the `lsp` related development will continue to happen on both `jupyterlab` and `jupyter-lsp` org for a period, I think we can postpone the transfer to the `jupyter-server` org. And as you said, I also want to move the server extension outside the monorepo `jupyterlab-lsp`. 
I'm on other stuff this week but I can get back to it next week.

**Comment by damianavila** [comment]
> Hi @krassowski, thanks for your clarification. I have no objection to keeping the jupyter-lsp server extension in the jupyter-lsp organization.

It seems there is agreement about keeping the jupyter-lsp server extension in the jupyter-lsp organization. 
Then, should we close this one?

**Comment by vidartf** [comment]
Closing as the discussion seems to have concluded
